language: node_js
node js:
    - "stable"
script: 
    - npm install 
    - npm test 
    - npm run build 

deploy: 
  provider: surge
  skip_cleanup: true
  domain: halting-loaf.surge.sh
  project: ./build/
  

on: 
  branch: master 

